In [64]:
import numpy as np

Дана целочисленная квадратная матрица. 
Определить:
произведение элементов в тех строках, которые не содержат отрицательных элементов:

In [57]:
N = 5

In [58]:
array = (np.random.rand(N, N) * 10).astype(int)

In [59]:
array

array([[1, 8, 5, 2, 8],
       [4, 2, 5, 7, 9],
       [6, 1, 4, 2, 6],
       [0, 2, 6, 1, 1],
       [6, 4, 1, 4, 4]])

In [60]:
array[0][0] = 0

In [61]:
array

array([[0, 8, 5, 2, 8],
       [4, 2, 5, 7, 9],
       [6, 1, 4, 2, 6],
       [0, 2, 6, 1, 1],
       [6, 4, 1, 4, 4]])

In [62]:
array[(array > 0).all(axis=1)].prod(axis=1)

array([2520,  288,  384])

Максимум среди сумм элементов диагоналей, параллельных главной диагонали матрицы:

In [63]:
max([np.diagonal(array, offset=i).sum() for i in range(-N + 1, N)])

18